message(STATUS "")
message(STATUS "")
message(STATUS "Information Summary:")
message(STATUS "")
message(STATUS "CMake Variables:")
message(STATUS "  - generator:      ${CMAKE_GENERATOR}(${CMAKE_BUILD_TOOL})")
message(STATUS "  - c++ compiler:   ${CMAKE_CXX_COMPILER}(${CMAKE_CXX_COMPILER_VERSION})")
message(STATUS "  - build type:     ${CMAKE_BUILD_TYPE}")

if(CMAKE_BUILD_TYPE)
    string(TOUPPER ${CMAKE_BUILD_TYPE} UPPERCASE_BUILD_TYPE)
    message(STATUS "  - CMAKE_C_FLAGS_${UPPERCASE_BUILD_TYPE}: ${CMAKE_C_FLAGS_${UPPERCASE_BUILD_TYPE}}")
    message(STATUS "  - CMAKE_CXX_FLAGS_${UPPERCASE_BUILD_TYPE}: ${CMAKE_CXX_FLAGS_${UPPERCASE_BUILD_TYPE}}")
else()
    message(STATUS "  - CMAKE_CXX_FLAGS: ${CMAKE_CXX_FLAGS}")
endif()

message(STATUS "  - install prefix: ${CMAKE_INSTALL_PREFIX}")
message(STATUS "    ")
message(STATUS "Options:")
# message(STATUS "  - PLAIN_BUILD_TESTS:  ${PLAIN_BUILD_TESTS}")
# message(STATUS "  - PLAIN_USE_ASAN:     ${PLAIN_USE_ASAN}")
message(STATUS "")
